sudo: false
language: node_js
before_install:
  - if [ $TRAVIS_OS_NAME != "linux" ]; then
      git clone https://github.com/creationix/nvm.git /tmp/.nvm;
      source /tmp/.nvm/nvm.sh;
    fi
node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'
  - '0.8'
os:
  - linux
  - osx
