language: node_js
node_js:
- 'iojs-1.5'
- '0.12'
- '0.11'
- '0.10'
- '0.8'
notifications:
  hipchat:
    notify: true
    rooms:
      secure: 67y1svakTOqrni4oA71NFujOf7Tx6zi1Lbkp8F99WyCg+/FOtZ5rOLR5Rtpl9NlPPkdYzkWDb2Xob9rpTjYXSVncv3nEToa6WjvqT0qdDW2/D+HvFmy4czArvm2+gnXKOlVJntpmVMcXcvc7uOgDiUiXRFYTLP6dB5jnwvK0P60=

